### ISSUE TITLE
Apparence of invalid fields ?

### ISSUE THREAD

**Issue by leplatrem** [Kinto/kinto-admin#502]
In #496 I added this CSS rule:

```css
input:invalid, input:focus:invalid {
  box-shadow: 0 0 5px 1px red;
}
```

And it made me realized that we had many places where forms are loaded with invalid values (usually empty strings :))

![screenshot from 2018-03-28 09-51-07](https://user-images.githubusercontent.com/546692/38048925-acd8a902-327b-11e8-8038-971a50155865.png)

What should we do? Should we highlight them in red?
