### ISSUE TITLE
Error `Cannot read property 'username' of undefined` after logout

### ISSUE THREAD

**Issue by cpxPratik** [Kinto/kinto-admin#577]
Signing with basic auth then logging out, then cannot sign back in. Show error as in the pic.

`docker-compose.yml`

```
db:
  environment:
    PGDATA: /var/lib/postgresql/data/pgdata
    POSTGRES_DB: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_USER: postgres
  image: postgres
  volumes:
    - ./postgresql/data:/var/lib/postgresql/data
web:
  image: kinto/kinto-server
  links:
   - db
  ports:
   - "8848:8888"
  volumes:
    - ./config:/etc/kinto

```
`./config/kinto.ini`

```
[server:main]
use = egg:waitress#main
host = 0.0.0.0
port = %(http_port)s

[app:main]
use = egg:kinto

kinto.cache_backend = kinto.core.cache.postgresql
kinto.cache_url = postgres://postgres:postgres@db/postgres
kinto.storage_backend = kinto.core.storage.postgresql
kinto.storage_url = postgres://postgres:postgres@db/postgres
kinto.permission_backend = kinto.core.permission.postgresql
kinto.permission_url = postgres://postgres:postgres@db/postgres

kinto.includes = kinto.plugins.default_bucket
                 kinto.plugins.admin
#                kinto.plugins.accounts
#                kinto.plugins.history
#                kinto.plugins.quotas

```
![kintoadminerror](https://user-images.githubusercontent.com/6893334/43312221-541a3fca-91ac-11e8-9d3a-acdf2a7f4d1d.png)

If I open new tab and paste the URL then I can sign in from there.
